services:
  app:
    build: .
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - target: 80
        published: ${HTTP_PORT:-4321}
        protocol: tcp
    volumes:
      - ./config/jwt:/app/config/jwt:ro
    environment:
      SERVER_NAME: ":80"
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$'
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:18-alpine
    volumes:
      - database_data:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  database_data:
